name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Rust tools
        run: |
          cargo install wasm-pack --version 0.13.1 --locked || true

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Verify Wrangler installation
        run: |
          echo "Wrangler version:"
          wrangler --version
          echo "Wrangler installation verified"

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            worker/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('.github/workflows/deploy.yml') }}

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build wasm assets
        run: npm run build:wasm-assets

      - name: Run all tests
        run: npm run check

      - name: Build
        run: npm run build:cf
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Verify database status
        run: |
          echo "Database is already properly configured with games table"
          echo "Migration 0000_legal_titania.sql was applied on 2025-07-18"
          echo "Skipping migration step as database is up to date"
        continue-on-error: true

      - name: Deploy Frontend
        run: wrangler deploy --config wrangler.toml --env=""
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
